### ISSUE TITLE
Appending to Carray containg text and Nones causes error

### ISSUE THREAD

**Issue by jefsayshi** [Blosc/bcolz#182] opened 2015-04-30 18:11 UTC
If a Carray consists of text and Nones, it works correctly until you try to append additional data on the end.

Bcolz Version: 0.8.1

System details:
Python 2.7.9 |Anaconda 2.1.0 (64-bit)| (default, Mar  9 2015, 16:20:48)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2

Code to reproduce and log:
```
>>> import bcolz
>>> b1 = bcolz.carray(["Hello", None])
>>> b2 = bcolz.carray(["World"])
>>> b1
carray((2,), object)
  nbytes: 16; cbytes: 304; ratio: 0.05
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[Hello None]
>>> b2
carray((1,), |S5)
  nbytes: 5; cbytes: 16.00 KB; ratio: 0.00
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
['World']
>>> b1.append(b2)
>>> b1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bcolz/carray_ext.pyx", line 2582, in bcolz.carray_ext.carray.__repr__ (bcolz/carray_ext.c:31524)
  File "bcolz/carray_ext.pyx", line 2570, in bcolz.carray_ext.carray.__str__ (bcolz/carray_ext.c:31219)
  File "/path/anaconda/lib/python2.7/site-packages/bcolz/arrayprint.py", line 468, in array2string
    separator, prefix, formatter=formatter)
  File "/path/anaconda/lib/python2.7/site-packages/bcolz/arrayprint.py", line 262, in _array2string
    data = ravel(a[:])  # read in otherwise we have an object array
  File "bcolz/carray_ext.pyx", line 1949, in bcolz.carray_ext.carray.__getitem__ (bcolz/carray_ext.c:24559)
  File "bcolz/carray_ext.pyx", line 1816, in bcolz.carray_ext.carray.getitem_object (bcolz/carray_ext.c:23016)
  File "bcolz/carray_ext.pyx", line 1813, in bcolz.carray_ext.carray.getitem_object (bcolz/carray_ext.c:22921)
  File "/path/anaconda/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/path/anaconda/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/path/anaconda/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
  File "/path/anaconda/lib/python2.7/site-packages/bcolz/utils.py", line 157, in build_carray
    return carray(rootdir=rootdir)
  File "bcolz/carray_ext.pyx", line 982, in bcolz.carray_ext.carray.__cinit__ (bcolz/carray_ext.c:13068)
ValueError: You need at least to pass an array or/and a rootdir
```

**Comment by esc** [comment] 2015-05-02 13:13
This is a problem with the object type, if you use another type, e.g. ``int64`` it works fine:

```
In [19]: b1 = bcolz.carray([1, 2])

In [20]: b1
Out[20]: 
carray((2,), int64)
  nbytes: 16; cbytes: 16.00 KB; ratio: 0.00
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[1 2]

In [21]: b2 = bcolz.carray([3])

In [22]: b1.append(b2)

In [23]: b1
Out[23]: 
carray((3,), int64)
  nbytes: 24; cbytes: 16.00 KB; ratio: 0.00
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[1 2 3]

```

I think what happens, is that it attempts to add the carray itself to the other carray and then fails when trying to extract it again, presumably not being able to unpickle the carray.

**Comment by esc** [comment] 2015-05-02 13:15
Yeah, it seems a problem with the pickle:

```
In [28]: b1 = bcolz.carray([1, 2])

In [29]: import pickle

In [30]: e = pickle.dumps(b1)

In [31]: pickle.loads(e)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-e46c0eaffbb9> in <module>()
----> 1 pickle.loads(e)

/home/esc/anaconda/envs/bcolz/lib/python2.7/pickle.pyc in loads(str)
   1380 def loads(str):
   1381     file = StringIO(str)
-> 1382     return Unpickler(file).load()
   1383 
   1384 # Doctest

/home/esc/anaconda/envs/bcolz/lib/python2.7/pickle.pyc in load(self)
    856             while 1:
    857                 key = read(1)
--> 858                 dispatch[key](self)
    859         except _Stop, stopinst:
    860             return stopinst.value

/home/esc/anaconda/envs/bcolz/lib/python2.7/pickle.pyc in load_reduce(self)
   1131         args = stack.pop()
   1132         func = stack[-1]
-> 1133         value = func(*args)
   1134         stack[-1] = value
   1135     dispatch[REDUCE] = load_reduce

/home/esc/gw/bcolz/bcolz/utils.pyc in build_carray(rootdir)
    158     """
    159     from bcolz import carray
--> 160     return carray(rootdir=rootdir)
    161 
    162 

/home/esc/gw/bcolz/bcolz/carray_ext.pyx in bcolz.carray_ext.carray.__cinit__ (bcolz/carray_ext.c:13023)()
    995             _new = False
    996         else:
--> 997             raise ValueError(
    998                 "You need at least to pass an array or/and a rootdir")
    999 

ValueError: You need at least to pass an array or/and a rootdir
```

**Comment by esc** [comment] 2015-05-02 13:20
So, currently only on-disk carrays can be pickled.

**Comment by esc** [comment] 2015-05-18 15:25
This may be fixed by #194 which was just merged to master. Please check it out and let us know if the issue is still present.

**Comment by jefsayshi** [comment] 2015-05-19 12:47
The error is gone, but I think the results are unexpected, because it sticks the array inside of the array instead of just appending the elements to the end: [Hello None ['World']]

Log:
Python 2.7.8 |Anaconda 2.1.0 (64-bit)| (default, Aug 21 2014, 18:22:21)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import bcolz
>>> print bcolz.__version__
0.10.0.dev0
>>> b1 = bcolz.carray(["Hello", None])
>>> b2 = bcolz.carray(["World"])
>>> b1
carray((2,), object)
  nbytes: 16; cbytes: 304; ratio: 0.05
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[Hello None]
>>> b2
carray((1,), |S5)
  nbytes: 5; cbytes: 16.00 KB; ratio: 0.00
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
['World']
>>> b1.append(b2)
>>> b1
carray((3,), object)
  nbytes: 199; cbytes: 631; ratio: 0.32
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[Hello None ['World']]
>>>

**Comment by esc** [comment] 2015-05-19 14:21
I see what you are saying, and on second thoughts, I think the semantics are broken for basic types

We should strive to provide pythonic behaviour for carrays:

For example for lists:

```
In [38]: a = [1, 2]

In [39]: b = [3]

In [40]: a.append(b)

In [41]: a
Out[41]: [1, 2, [3]]

In [42]: a.extend(b)

In [43]: b
Out[43]: [3]

In [44]: a
Out[44]: [1, 2, [3], 3]
```

I.e. the semantic difference between ``append`` and ``extend``.

**Comment by esc** [comment] 2015-05-19 14:23
@FrancescAlted how would you feel about closing this one now and taking the discussion to the mailinglist?

**Comment by jefsayshi** [comment] 2015-05-19 16:15
I see what you are saying, but append acts likes extend for integers, so it just needs to be consistent

```
Python 2.7.9 |Anaconda 2.1.0 (64-bit)| (default, Mar  9 2015, 16:20:48)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import bcolz
>>> print bcolz.__version__
0.8.1
>>> b1 = bcolz.carray([1, 2])
>>> b2 = bcolz.carray([3])
>>> b1
carray((2,), int64)
  nbytes: 16; cbytes: 16.00 KB; ratio: 0.00
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[1 2]
>>> b2
carray((1,), int64)
  nbytes: 8; cbytes: 16.00 KB; ratio: 0.00
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[3]
>>> b1.append(b2)
>>> b1
carray((3,), int64)
  nbytes: 24; cbytes: 16.00 KB; ratio: 0.00
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[1 2 3]
>>>
```

**Comment by esc** [comment] 2015-05-19 16:16
I agree, it should be consistent.

**Comment by FrancescAlted** [comment] 2015-05-20 07:45
My initial thought was that `carray.append()` would provide Python append or extend, depending on if you pass a single element or a list.  I did this just for simplicity and whether or not this should be acceptable could a matter of discussion, so feel free to initiate a discussion in the mailing list.

**Comment by esc** [comment] 2015-05-23 03:55
Closing this, because the original issue is solved.

**Closed by esc** 2015-05-23 03:55 UTC
Labels: bug
