### ISSUE TITLE
Very poor performance with cross-drive NTFS junctions if rootdir not in working directory

### ISSUE THREAD

**Issue by ARF1** [Blosc/bcolz#128] opened 2015-01-30 00:34 UTC
I am converting a 56 MB lvl1 bzip2-compressed pytables file to bcolz. In the process I observed a 260% slow-down depending on the rootdir parameter:

```
import bcolz
%timeit -n1 -r1 db = bcolz.ctable.fromhdf5('mydata.h5', '/mydata/table', rootdir='mydata.bcolz', cparams=bcolz.cparams(cname='zlib', clevel=9))
1 loops, best of 1: 2min 58s per loop

%timeit -n1 -r1 db = bcolz.ctable.fromhdf5('mydata.h5', '/mydata/table', rootdir='..\mydata.bcolz', cparams=bcolz.cparams(cname='zlib', clevel=9))
1 loops, best of 1: 7min 56s per loop

cd ..
%timeit -n1 -r1 db = bcolz.ctable.fromhdf5('mydir\mydata.h5', '/mydata/table', rootdir='mydata.bcolz', cparams=bcolz.cparams(cname='zlib', clevel=9))
1 loops, best of 1: 2min 52s per loop

bcolz.__version__
'0.7.3.dev'
```

**Comment by esc** [comment] 2015-01-30 01:00
I can't imagine why the location of the rootdir should make any difference. Anyhow, two ideas come to mind:

1) You may be seeing a measurement error since you are not flushing and syncing the filesystem buffers as part of ``timeit``. What operating system are you running this on? What filesystem? Also could you paste the output of ``bcolz.print_versions()``. 

2) Would it be possible to get at the data or maybe a script to generate something similar, in order to reproduce the error?

**Comment by ARF1** [comment] 2015-01-30 12:02
Ok, I think I am getting closer to the source of this. First up though, the requested `bcolz.print_versions()` output:

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
bcolz version:     0.7.3.dev
NumPy version:     1.9.1
Blosc version:     1.4.1 ($Date:: 2014-07-08 #$)
Blosc compressors: ['blosclz', 'lz4', 'lz4hc', 'snappy', 'zlib']
Numexpr version:   2.3.1
Python version:    2.7.9 |Anaconda 2.1.0 (32-bit)| (default, Dec 18 2014, 17:00:07) [MSC v.1500 32 bit (Intel)]
Byte-ordering:     little
Detected cores:    2
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

System is:
```
python --version
Python 2.7.9 :: Anaconda 2.1.0 (32-bit)
```

Running on Windows 8.1 32-bit, filesystem NTFS, on magnetic (i.e. non-SSD) hard drive.

# Analysis
I am coming to believe that the issue lies with the windows api when the processes' working directory is different from the directory of the file system operations in NTFS junction subdirectories:

Setup:
Disk 0: NTFS system partition on SSD mounted as `C:\`
Disk 1: NTFS data partition on magnetic HDD

Disk 1 is mounted as a NTFS junction point in `C:\Users\Me\Documents` and also separately as `Z:\`.

**Observing general Windows problems with cross-drive NTFS junctions:**
Bcolz rootdir: `C:\Users\Me\Documents\abc\def\mydata.bcolz`
1. Working directory: `C:\Users\Me\Documents\abc\def`: executing `rmdir /Q /S mydata.bcolz` is a IO bound operation
2. Working directory: `C:\Users\Me\Documents\abc\def\xyz`: executing `rmdir /Q /S ..\dailyPrices.bcolz` is a CPU bound operation

In the first case, the `cmd.exe` process hardly consumes any CPU time, while in the latter it consumes 100% of one core.

But note:
3. Working directory: `Z:\abc\def\xyz`: executing `rmdir /Q /S ..\dailyPrices.bcolz` is again an IO bound operation!

**The issue is further illustrated by profiler runs with different rootdir parameters:**
*Rootdir in working directory (in subdirectory of a NTFS junction):*
```
%prun db = bcolz.ctable.fromhdf5('mydata.h5', '/mydata/table', rootdir='mydata.bcolz', cparams=bcolz.cparams(cname='zlib', clevel=9))
          1500564 function calls (1500193 primitive calls) in 188.167 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    62560  157.277    0.003  167.626    0.003 {method 'append' of 'bcolz.carray_ext.carray' objects}
     3680   17.264    0.005   17.264    0.005 {method '_read_records' of 'tables.tableextension.Table' objects}
```

*Rootdir not in working directory but in subdirectory of a NTFS junction:*
```
%prun db = bcolz.ctable.fromhdf5('mydata.h5', '/mydata/table', rootdir='..\\mydata.bcolz', cparams=bcolz.cparams(cname='zlib', clevel=9))
          1500564 function calls (1500193 primitive calls) in 462.474 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    62560  430.113    0.007  441.088    0.007 {method 'append' of 'bcolz.carray_ext.carray' objects}
     3680   17.449    0.005   17.449    0.005 {method '_read_records' of 'tables.tableextension.Table' objects}
```

*Rootdir not in working directory and NOT in subdirectory of a NTFS junction:*
```
In [40]: %prun db = bcolz.ctable.fromhdf5('mydata.h5', '/mydata/table', rootdir='..\\mydata.bcolz', cparams=bcolz.cparams(cname='zlib', clevel=9))
          1500564 function calls (1500193 primitive calls) in 191.624 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    62560  160.449    0.003  170.931    0.003 {method 'append' of 'bcolz.carray_ext.carray' objects}
     3680   17.373    0.005   17.373    0.005 {method '_read_records' of 
```

My guess is that this cannot really be fixed in bcolz. (At least without modifying the process working directory within bcolz which would clearly be asking for trouble...) Maybe a warning could be added to the documentation to avoid rootdirs located below cross-disk NTFS junctions?

**Comment by esc** [comment] 2015-02-16 21:49
I am not really sure how to proceed with this one. We could add something to the documentation, I guess, although I am scared that this might rot away.

**Comment by esc** [comment] 2015-05-23 04:04
Closing this, feel free to submit the enhancements to the documentation as a pull-request.

**Closed** 2015-05-23 04:04 UTC
